### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by MatthewLee-MDDP** [AuScalableDroneCloud/Tracker#11]
There appears to be an Authentication issue preventing me from logging in
![Untitledxxx](https://user-images.githubusercontent.com/97568659/153079842-7b81c6d3-787b-4b55-9f27-bd49b7c7729c.jpg)
![Untitledxxx](https://user-images.githubusercontent.com/97568659/153080146-38c85398-58f0-4069-a469-96ba2107887e.jpg)

**Comment by OKaluza** [comment]
There is a typo in your email: moansh instead of monash, I used the admin account to correct it, if you try again it should trigger resending the verification email.
