### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by pariscapell** [AuScalableDroneCloud/Tracker#12]
Hi ASDC team,

Total rookie q- but I've just moved onto a new laptop and have lost the login link! I'm not looking for https://asdc.cloud.edu.au/login/ but the one that has 'continue with Aaf'. 

Cheers!

**Comment by OKaluza** [comment]
If you go to the home page https://asdc.cloud.edu.au it should
automatically redirect you, but it looks like there is a problem with our
auth provider at the moment, I'll look into it and hopefully have it
resolved soon.

**Comment by OKaluza** [comment]
Hi @pariscapell all fixed now, let me know if you still have trouble loggin in.
