### ISSUE TITLE
Opening Cesium via ASDC dashboard link does not automatically log user in to Cesium and manual login then crashes the web page.

### ISSUE THREAD

**Issue by TimeScience** [AuScalableDroneCloud/Tracker#18]
To reproduce 
(1) Launch Cesium from the dashboard link in ASDC
(2) Open the "webODM" projects tab in Cesium iframe.
(3) Click log in and the page dies with error "_asdc.cloud.edu.au redirected you too many times._"
(also can be replicated by going to this url:   https://asdc.cloud.edu.au/plugins/asdc/cesium/)

**Comment by OKaluza** [comment]
This is deprecated, we don't run cesium in an iframe anymore (it was just an experiment) see https://dev.asdc.cloud.edu.au
If you wan to use this mode I'm happy to fix and re-enable it in dev, but currently dev just opens cesium in a new tab.

**Comment by TimeScience** [comment]
no worries. I think it is much better to open a new tab for now.
