### ISSUE TITLE
Import from cloud store doubles image count

### ISSUE THREAD

**Issue by TimeScience** [AuScalableDroneCloud/Tracker#19]
Imported dataset of 505 images from cloudstor. ODM crashes with error
"1010 images uploaded, but this node can only process up to 1000."
I doble checked there are only 505 images in the folder. This wasn't a duplicated task or anything, just a new task created via the "cloud import" button. 
This is on the dev branch

@OKaluza, this dataset should already be shared with you but I'm not sure what the URL will look like to you

Something like:
_ANU-APPF-NCRIS/Drone and other Data/USLN/BVZ-USLN-COOLAMA-2022-02-11-P4M-TB/Originals/images-jpg_

**Comment by OKaluza** [comment]
Same duplicate image bug that has now been fixed

**Comment by TimeScience** [comment]
Awesome, thanks!
