### ISSUE TITLE
Missing images from older Task

### ISSUE THREAD

**Issue by TimeScience** [AuScalableDroneCloud/Tracker#23]
https://asdc.cloud.edu.au/dashboard/?page=4&project_task_open=52&project_task_expanded=d7d20c75-2a06-48a6-8946-6efc9cff341c

Image missing when I try and rerun this task. 

Task was uploaded from cloudstor near the start of the project, so it may have been lost in the shuffle during upgrades, etc. But let me know if the images are actually there or not and I can re-upload if needed.

Thanks

**Comment by OKaluza** [comment]
Hi Tim, unfortunately I lost that data and a few other older projects in a mix up during the move to using 100% object storage, I sent you a list at the time
https://asdc-world.slack.com/archives/C01KXFP5B4N/p1655791376079579?thread_ts=1655443452.013239&cid=C01KXFP5B4N
