### ISSUE TITLE
Task level buttons to "Edit in Jupyer hub" and "Open notebook" don't do anything other than launch jupyter

### ISSUE THREAD

**Issue by TimeScience** [AuScalableDroneCloud/Tracker#24]
What's the intended behaviour here and what is the difference between Open Notebook and Edit in Jupyter?
Can these be merged into one button?

I think ideally these buttons would map the files from a Task into the user's directory structure in Jupyter (probaby as Read Only?) and also provide a code snippet for programatically accessing the data including an output path that goes to a different folder than the read only ODM folder.

This should be another topic/issue, but we need to decide what folder structure we want to maintain w/in jupyter... we also need to think through how much we want to hand hold users to avoid them accidentally killing existing completed Task data but also let them write out ODM-friendly data if the want to and know how to do it.

**Comment by OKaluza** [comment]
Edit in Jupyter has been removed, Open in Notebook is still active and the sample notebook fixed, may decide to remove it in the future.
Feel free to open an issue here or on jira to discuss how to handle file access via jupyterhub.
