### ISSUE TITLE
Duplicating tasks is slow and often times out and fails

### ISSUE THREAD

**Issue by TimeScience** [AuScalableDroneCloud/Tracker#25]
Bug isn't 100% of the time but reasonably frequent. Let me know if there is anything I can do to provide more detailed information on this issue.
Task ID for this failed "copy" was 4f3a6cb0-6b47-4dfc-9d10-fb84076245b3

![image](https://user-images.githubusercontent.com/3067588/212807794-9c8d7a83-a591-41af-a91a-389c42a9cf25.png)

**Comment by OKaluza** [comment]
I'm closing this as the duplication feature was reworked (as discussed) to use references to the original task source images and skip copying the output assets altogether - this still allows running a new set of parameters to generate a new set of outputs while saving the storage overhead and processing time of copying all the inputs, duplication is now pretty much instantaneous.

**Comment by TimeScience** [comment]
Duplication is really fast now.
But now that I've used it a bit, from a UI persepctive, I think we need some user feedback on what is actually duplicated because it isn't clear within the copied task that most of the outputs aren't copied over. 
Not sure the best way to implement this... seems like we need a note in the popup when the user duplicates the task, letting them know that it own't contain the outputs. and then maybe a way within the new Task to indicated that is doesn't have outputs?

Not sure if this latter aspect needs its own issue... this is a bit of a general problem for ASDC since we use tasks in non-standard ways and since the webODM UI just treats all Tasks the same. As a user, it is confusing when non-standard tasks don't behave like a normal Task (ie have no image count, or for duplicated tasks, they still have the View Map and  3D button but it doesn't work - or does it link back to the other tasks' data? I can see that getting confusing)

Would it be feasible to remove the buttons for data that the task doesn't have (ie "View Map" and "View 3D model), or is there a better way to solve this?

**Comment by OKaluza** [comment]
Sure, this issue is probably not where this needs to be brought up. it's really a documentation issue and all these concerns relate to lack of proper documentation, be it in the form of a manual or inline help and popups for users.
 
View Map and View 3D model should not appear unless there is map and 3d model data, if they are appearing this is a separate bug/issue.
