### ISSUE TITLE
For non photogrammetry tasks, remove image counts and time labels and add labelling about what the task type is

### ISSUE THREAD

**Issue by TimeScience** [AuScalableDroneCloud/Tracker#40]

**Comment by OKaluza** [comment]
https://github.com/AuScalableDroneCloud/WebODM/commit/9f9b1e35572a3b4a0d6b34611da0ceb77f3f6d45
https://github.com/AuScalableDroneCloud/WebODM/commit/bf2a7355656489e012d8c6273280b94879abadb3

**Comment by TimeScience** [comment]
That looks good. Thanks.

Thinking about how to provide better transparency for users with non webODM data... would it be hard to run the _files.json_ 
 file through code that took the Unique list of file types and then add that as text list to particular task? 

For example the set of file types of the below dataset would be something like:
[JPG, JSON, LAZ, GEOJSON, GPKG, JSON, TXT, GLB, PNG]

It isn't a perfect solution, but it seems like it could be a fast way provide more transparency at a glance at the Task level, for non-standard Tasks without having to do a bunch of extra UI work. See for example the code below (courtesy of chatGPT :) )

`import json
import os
from pathlib import Path

# Load the JSON file
with open('filelist.json', 'r') as f:
    data = json.load(f)

# Extract the file extensions from the list of file paths
extensions = set()
for file_path in data['files']:
    extension = Path(file_path).suffix[1:].upper()
    extensions.add(extension)

`


Example data:
{"custom_assets": {}, "files": ["DJI_0001.JPG", "DJI_0436.JPG", "DJI_0437.JPG", "DJI_0438.JPG", "assets/cameras.json", "assets/files.json", "assets/images.json", "assets/log.json", "assets/task_output.txt", "assets/entwine_pointcloud/ept-build.json", "assets/entwine_pointcloud/ept-data/7-91-73-62.laz", "assets/entwine_pointcloud/ept-data/7-91-74-62.laz", "assets/entwine_pointcloud/ept-data/7-91-75-62.laz", "assets/entwine_pointcloud/ept-data/7-91-76-62.laz", "assets/odm_georeferencing/odm_georeferenced_model.bounds.geojson", "assets/odm_georeferencing/odm_georeferenced_model.bounds.gpkg", "assets/odm_georeferencing/odm_georeferenced_model.info.json", "assets/odm_georeferencing/odm_georeferenced_model.laz", "assets/odm_georeferencing/odm_georeferenced_model.summary.json", "assets/odm_georeferencing/odm_georeferencing_model_geo.txt", "assets/odm_georeferencing/proj.txt", "assets/odm_orthophoto/odm_orthophoto.tif", "assets/odm_report/report.pdf", "assets/odm_report/shots.geojson", "assets/odm_report/stats.json", "assets/odm_texturing/odm_textured_model.mtl", "assets/odm_texturing/odm_textured_model_geo.conf", "assets/odm_texturing/odm_textured_model_geo.glb", "assets/odm_texturing/odm_textured_model_geo.mtl", "assets/odm_texturing/odm_textured_model_geo.obj", "assets/odm_texturing/odm_textured_model_geo_material0015_map_Kd.png", "assets/odm_texturing/odm_textured_model_geo_material0017_map_Kd.png"]}

**Comment by OKaluza** [comment]
If you want a list of available file extensions we can add it with a couple of lines of code, there's already a custom icon if there are.mp4 files as an example of this sort of thing, no need to invoke ChatGPT it really doesn't add anything but noise :D  
files.json doesn't actually exist in the project files, it's an api endpoint object that serves a json file.
It's probably more helpful to just list all custom assets in the task info for tasks with no input images

**Comment by TimeScience** [comment]
sorry for the gpt noise... as a non-coder it is interesting to see what things it can do easily:)

Is it possible to list _all_ the assets? (ie regular ones and custom ones?) 
We need a way to better demarcate which Tasks are regular ODM tasks and which ones aren't. So like for a duplicated Task, it would be good to be able to show people that it doesn't have the usual assets.
And likewise for uploaded data, or Tasks made via Cesium or Jupyter... it would be nice for users to be able to easily see what assets are in a given Task.
