### ISSUE TITLE
"View 3D" button now missing from dev

### ISSUE THREAD

**Issue by TimeScience** [AuScalableDroneCloud/Tracker#43]
For example this project has a point cloud but now button shows in UI:
![image](https://user-images.githubusercontent.com/3067588/226521934-59433ca0-4f85-4764-a377-3bb0fb726adc.png)

A similar project on the production branch has the button
![image](https://user-images.githubusercontent.com/3067588/226521850-fe06d10c-cfa8-4489-86ba-c8e6d73b666a.png)

**Comment by TimeScience** [comment]
Project ID of first project is project_task_expanded=d4d27aad-156c-43ca-8c15-5e61d705123b (@OKaluza , shared with you)

**Comment by OKaluza** [comment]
Thanks, now fixed https://github.com/AuScalableDroneCloud/WebODM/commit/8804a9f0f522b6b62ff62fa16a9af2cd3aabfc13 app rebuild in progress for dev

**Comment by TimeScience** [comment]
thanks!
________________________________

**Comment by OKaluza** [comment]
Fix is already live on dev, please close if it's working for you now

**Comment by TimeScience** [comment]
yes, seems to be fixed. thanks
