### ISSUE TITLE
Projects can't be shared with users if they have more than one ASDC account via different auth methods if the auth account has the same email address

### ISSUE THREAD

**Issue by TimeScience** [AuScalableDroneCloud/Tracker#6]
I have two ASDC account, one using my github for authentication and another using AAF. Since my github account is also under my ANU email (tim.brown@anu.edu.au) when people try to share a Project, they can see both my accounts but webODM doesn't permit Projects to be shared with my AAF account. To reproduce, try and share a project with my email
This may be a wider issue with how webODM implements account tracking, but I thought I'd raise it here first in case this is an issue with how we've implemented authentication.

**Comment by OKaluza** [comment]
I was able to share a project with both your projects without issues Tim, can you confirm if you are or are not able to access this test project?
![image](https://user-images.githubusercontent.com/6336397/144554001-c568a283-2fe7-4dfe-857f-a685a47be695.png)

**Comment by OKaluza** [comment]
This is no longer relevant as duplicate emails are not allowed in accounts, from now on a sign-on with a duplicate email will not create a new account but sign in to the existing one with matching email. (Note to self: we have to be careful with this to not allow use of any identity providers that do not verify email addresses and disable login without verified email)
